### ISSUE TITLE
(note: scheme tableau not found, using s2color)

### ISSUE THREAD

**Issue by gen-li** [asjadnaqvi/Stata-schemes#1]
Hi,

When I was trying to use white_tableau scheme in Stata17, it reported that 

(note: scheme tableau not found, using s2color)

Do you know how to solve the issue?

Thanks!

**Comment by asjadnaqvi** [comment]
Checking!

**Comment by asjadnaqvi** [comment]
Dear @gen-li, I doubled checked with a bunch of people using Stata 17 and the schemes are working fine. Please reinstall them. Also see if you can physically see in the the C:/ado/personal/s/ folder. Also make sure the names are correctly specified. If it still doesn't work send me a screenshot of the dofile please!
