### ISSUE TITLE
Set all schemes to 'off'

### ISSUE THREAD

**Issue by ShayAdams** [asjadnaqvi/Stata-schemes#3]
Hi There,
Just wondering whether its possible to turn schemes off after selecting one. 
Standard Stata code for similar (`trace, off` or `more, off` for instance) doesn't apply here.
Apologies if I've missed this.

regards, Shay

**Comment by asjadnaqvi** [comment]
Dear Shay, 
There is always one scheme defined. By off, I am assuming you mean reverting back to the default Stata's s2. Here you either need to set it at the beginning of a dofile or you can revert to the default permanently just by typing:

**set scheme s2color, perm**

You can also select a scheme just for one graph so you are not stuck with it all the time:
**scatter y x, scheme(s2color)**

Let me know if this helps!

Asjad

**Comment by ShayAdams** [comment]
Dear Asjad, This is perfect, appreciate the prompt reply.
The schemes are great, just wanted to ensure I could still customise my graphs individually against a background of the Stata default.
Shay
