### ISSUE TITLE
Failure to install

### ISSUE THREAD

**Issue by ericmelse** [asjadnaqvi/Stata-schemes#5]
Dear Asjad,

Thank you for the update (although I think that the Ukranian scheme colors are too saturated to be of use).
But, while exploring, I seem to have a problem with downloading from your Github server, the following:

`net d tsg_schemes, from("https://raw.githubusercontent.com/asjadnaqvi/Stata-schemes/main/schemes/")`

results in my Stata window (v. 17 rev. 06 Apr. 2022):

```
file
    https://raw.githubusercontent.com/asjadnaqvi/Stata-schemes/main/schemes/tsg_schemes.pkg not found
could not load tsg_schemes.pkg from https://raw.githubusercontent.com/asjadnaqvi/Stata-schemes/main/schemes/
r(601);
```

Likewise, using:

`net install tsg_schemes, from("https://raw.githubusercontent.com/asjadnaqvi/Stata-schemes/main/schemes/") replace
`

results in:

```
file
    https://raw.githubusercontent.com/asjadnaqvi/Stata-schemes/main/schemes/tsg_schemes.pkg not found
could not load tsg_schemes.pkg from https://raw.githubusercontent.com/asjadnaqvi/Stata-schemes/main/schemes/
r(601);
```

**Comment by asjadnaqvi** [comment]
Dear Eric,

Thank you for the feedback! I will desaturate the ukraine scheme. 

Regarding the paths, I updated them to be simpler. They are now as follows:
net install schemepack, from("https://raw.githubusercontent.com/asjadnaqvi/Stata-schemes/main/schemes/") replace

and

use "https://github.com/asjadnaqvi/Stata-schemes/blob/main/scheme_test.dta?raw=true", clear

Hope this helps!

Asjad
