### ISSUE TITLE
X-axis scaling issue

### ISSUE THREAD

**Issue by VanMNguyen** [asjadnaqvi/Stata-schemes#6]
I have just started using your amazing package, however, I encounter an issue where the x-axis do no scale properly (scaling from 0-8), however, I got a data point which has x-value greater then 8. Can you let me know how can I fix this? I have added xscale(range(0 (2) 10)) but it is not working. I am currently using your white_hue scheme.
I am not a regular github user so I do not know if raising the issue here is appropriate. Please understand. Thank you.
I am looking forward to hearing your response,
Van

![Graph](https://user-images.githubusercontent.com/112388780/187185539-f939ae27-b05e-415c-91cc-06c6b5d71729.png)

**Comment by asjadnaqvi** [comment]
Try xlabel(0(2)10)

**Comment by VanMNguyen** [comment]
It worked, so simple. Thank you very much Asjadnaqvi! 
Once again, amazing package. I used to spent hours customizing graphs. Thank you very much.
